"""empty message

Revision ID: 139ecf922ce2
Revises: f6a9b7368e9e
Create Date: 2019-05-05 18:38:32.835003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '139ecf922ce2'
down_revision = 'f6a9b7368e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['category_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###
