"""empty message

Revision ID: 444f0741e502
Revises: 5f4b034da683
Create Date: 2019-05-09 00:29:56.031500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '444f0741e502'
down_revision = '5f4b034da683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart', 'cart_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart', sa.Column('cart_id', mysql.CHAR(collation='utf8mb4_general_ci', length=32), nullable=False))
    # ### end Alembic commands ###
