"""empty message

Revision ID: 49bcbc4051ab
Revises: 139ecf922ce2
Create Date: 2019-05-05 21:54:03.130915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bcbc4051ab'
down_revision = '139ecf922ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'department', ['department_id'], ['department_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'department_id')
    # ### end Alembic commands ###
