"""empty message

Revision ID: f23387f6aeec
Revises: 444f0741e502
Create Date: 2019-05-09 00:30:17.244009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23387f6aeec'
down_revision = '444f0741e502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart', sa.Column('cart_id', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart', 'cart_id')
    # ### end Alembic commands ###
